#!/bin/sh

program='gsql'
version='(unversioned)'
logfile="/tmp/gsql84.log"

die() {
    echo "error: $@" >&2
    echo "error: $@" >> $logfile
    exit 1
}

OS=$(uname)
case $OS
in
    "Linux") echo "[0]os: $OS" >> ${logfile} 2>&1
    ;;
    *) die "$OS not supported"
    ;;
esac


sub_help(){
    echo "Usage: $program <subcommand> [options]\n"
    echo "Subcommands:"
    echo "    bar   Do bar"
    echo "    baz   Run baz"
    echo ""
    echo "For help with each subcommand run:"
    echo "$program <subcommand> -h|--help"
    echo ""
}

sub_init_echo_archives() {
    option=$1
    case $option
    in
        pg1016)  echo "https://ftp.postgresql.org/pub/source/v10.16/postgresql-10.16.tar.gz"
        ;;
        pg1111)  echo "https://ftp.postgresql.org/pub/source/v11.11/postgresql-11.11.tar.gz"
        ;;
        pg1206)  echo "https://ftp.postgresql.org/pub/source/v12.6/postgresql-12.6.tar.gz"
        ;;
        pg1302)  echo "https://ftp.postgresql.org/pub/source/v13.2/postgresql-13.2.tar.gz"
        ;;
        *     )  die "Unknown version $option"
        ;;
    esac
}


sub_in(){
    if [ ! $G_DEV_PATH ]
    then
        die "Need environment variable G_DEV_PATH"
    fi

    if [ $# != 2 ]
    then
        echo "USAGE: in [ver] [port]"
        echo "e.g. : in pg1016 8400"
	exit 1
    fi

    if type wget > /dev/null ; then
        fetch='wget'
    else
        fetch='curl -LO -u anonymous:'
    fi

    local port=$2
    [ ${port} ] ||  die "No port"
    local directory=${G_DEV_PATH}
    local addr=$(sub_init_echo_archives $1)
    local filename=${addr##*/}
    local filena=${filename::-7}
    echo "[1]check root directory" 2>&1 | tee -a ${logfile}
    [ -d "${directory}" ]          ||  die "No base directory: ${directory}"
    [ -d "${directory}/download" ] ||  mkdir ${directory}/download
    [ -d "${directory}/src" ]      ||  mkdir ${directory}/src
    [ -d "${directory}/data" ]     ||  mkdir ${directory}/data
    [ -d "${directory}/bin" ]      ||  mkdir ${directory}/bin
    echo "[2]download source code: $filename" 2>&1 | tee -a ${logfile}
    [ -e "${directory}/download/${filename}" ] || ${fetch} -O "${directory}/download/${filename}" "${addr}" >> ${logfile} 2>&1 || die "Cannot download ${filename} from ${addr}"
    echo "[3]unpack: $filename" 2>&1 | tee -a ${logfile}
    [ -d "${directory}/src/${filena}" ] || tar xzf "${directory}/download/${filename}" -C ${directory}/src/ >> ${logfile} 2>&1 || die "Cannot extract package from ${filename}"

    echo "[4]yum install" 2>&1 | tee -a ${logfile}
    sudo yum -y install coreutils glib2 lrzsz mpstat dstat sysstat e4fsprogs xfsprogs ntp readline-devel zlib-devel openssl-devel pam-devel libxml2-devel libxslt-devel python-devel tcl-devel gcc make smartmontools flex bison perl-devel perl-ExtUtils* openldap-devel jadetex openjade bzip2 >> ${logfile} 2>&1 || die "echo \"$USER ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers.d/test"

    echo "[5]sysctl"  2>&1 | tee -a ${logfile}

    echo "[6]configure port: ${port}" | tee -a ${logfile}
    cd ${directory}/src/${filena} && ./configure --prefix=${directory}/bin/$1 --with-pgport=${port} --enable-depend --enable-cassert --enable-debug CFLAGS="-ggdb -O0" >> ${logfile} 2>&1 || die "configure failed"

    echo "[7]make&make install" | tee -a ${logfile}
    cd ${directory}/src/${filena} && make -j16  >> ${logfile} 2>&1 || die "make failed"
    cd ${directory}/src/${filena} && make install >> ${logfile} 2>&1 || die "make install failed"

    echo "[8]initdb" | tee -a ${logfile}
    # initdb -D ${pgdata} -E UTF8 --lc-collate=C --lc-ctype=en_US.utf8 -U postgres -X /io/pgxlog
    local pgbin=${directory}/bin/$1/bin
    local pgdata=${directory}/data/pg${port}
    ${pgbin}/initdb -D ${pgdata} -E UTF8 --lc-collate=C --lc-ctype=en_US.utf8 -X ${pgdata}/pgxlog${port} >> ${logfile} 2>&1 || die "Initdb failed"

    echo "[9]config db" | tee -a ${logfile}
    sed -ir "s/#*port.*/port = ${port}/" ${pgdata}/postgresql.conf
    sed -ir "s/#*listen_addresses.*/listen_addresses = '0.0.0.0'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*unix_socket_directories.*/unix_socket_directories = '.'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*superuser_reserved_connections.*/superuser_reserved_connections = 13/" ${pgdata}/postgresql.conf
    sed -ir "s/#*logging_collector.*/logging_collector= on/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_directory.*/log_directory = 'pg_log'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_filename.*/log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_rotation_size.*/log_rotation_size = 10MB/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_line_prefix.*/log_line_prefix='%p %r %u %d %t %e'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_min_duration_statement.*/log_min_duration_statement= 1000/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_timezone.*/log_timezone = 'UTC'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_truncate_on_rotation.*/log_truncate_on_rotation = on/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_rotation_age.*/log_rotation_age = 0/" ${pgdata}/postgresql.conf
    sed -ir "s/#*log_statement.*/log_statement= 'all'/" ${pgdata}/postgresql.conf
    sed -ir "s/#*max_prepared_transactions.*/max_prepared_transactions= 800/" ${pgdata}/postgresql.conf

    echo "[10]start db" | tee -a ${logfile}
    ${pgbin}/pg_ctl start -D ${pgdata} >> ${logfile} 2>&1 || die "Startdb failed"

}

sub_ps(){
    if [ ! $G_DEV_PATH ]
    then
        die "Need environment variable G_DEV_PATH"
    fi

    if [ $# != 2 ]
    then
        echo "USAGE: ps [ver] [port]"
        echo "e.g. : ps pg1016 8400"
	exit 1
    fi

    local port=$2
    [ ${port} ] ||  die "No port"
    local directory=${G_DEV_PATH}
    local pgbin=${directory}/bin/$1/bin
    ${pgbin}/psql -h127.0.0.1 -p${port} postgres
}

sub_gd(){
    if [ ! $G_DEV_PATH ]
    then
        die "Need environment variable G_DEV_PATH"
    fi

    if [ $# != 1 ]
    then
        echo "USAGE: gd [ver]"
	echo "e.g. : gd pg1016"
	exit 1
    fi

    local directory=${G_DEV_PATH}
    local pgbin=${directory}/bin/$1/bin
    local processid=$(ps -ef --sort=lstart | egrep [p]ostgres | tail -n 1 | awk '{print $2}')
    gdb ${pgbin}/postgres ${processid}
}

sub_re(){
    if [ ! $G_DEV_PATH ]
    then
        die "Need environment variable G_DEV_PATH"
    fi

    if [ $# != 2 ]
    then
        echo "USAGE: rs [ver] [port]"
        echo "e.g. : rs pg1016 8400"
	exit 1
    fi

    local port=$2
    [ ${port} ] ||  die "No port"
    local directory=${G_DEV_PATH}
    local pgbin=${directory}/bin/$1/bin
    local pgdata=${directory}/data/pg${port}
    ${pgbin}/pg_ctl restart -D ${pgdata}
}


sub_stop(){
    echo "stop"
}



subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        sub_${subcommand} $@
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            echo "       Run '$program --help' for a list of known subcommands." >&2
            exit 1
        fi
        ;;
esac
